default: &default
  adapter: postgresql
  encoding: unicode
  pool: 20
  host: localhost
  username: sam
  password: samiralak


development:
  <<: *default
  database: portfolio_development

test:
  <<: *default
  database: portfolio_test

production:
  <<: *default
  database: portfolio_production
